<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>comment</key>
    <string>Wiz Syntax</string>
    <key>fileTypes</key>
    <array>
        <string>wiz</string>
    </array>
    <key>foldingStartMarker</key>
    <string>^\s*\b(function|local\s+function|if|for)\b|{[ \t]*$|\[\[</string>
    <key>foldingStopMarker</key>
    <string>\bend\b|^\s*}|\]\]</string>
    <key>keyEquivalent</key>
    <string>^~W</string>
    <key>name</key>
    <string>Wiz</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.wiz</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.scope.wiz</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(def)\s+([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
            <key>name</key>
            <string>meta.function.wiz</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.wiz</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>support.class.wiz</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(package|func|task)\s+([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
            <key>name</key>
            <string>meta.function.wiz</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.wiz</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.scope.wiz</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(let)\s+([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
            <key>name</key>
            <string>meta.function.wiz</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.wiz</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.scope.wiz</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.wiz</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(in)\s+([a-zA-Z_][a-zA-Z_0-9]*)\b</string>
            <key>name</key>
            <string>meta.function.wiz</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>\b(var|bank)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.wiz</string>
                </dict>
            </dict>
            <key>contentName</key>
            <string>meta.variable.wiz</string>
            <key>end</key>
            <string>(\:)\s*([a-zA-Z_][a-zA-Z_0-9]*)</string>
            <key>endCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.operator.wiz</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.wiz</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.function.scope.wiz</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.wiz</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>\b([a-zA-Z_][a-zA-Z_0-9]*)\s*(?:(,)|(?=[\n\:]))</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>match</key>
            <string>(\b0x[a-fA-F0-9]+\b|\b[0-9]+\b|\b0b[0-1]+\b)</string>
            <key>name</key>
            <string>constant.numeric.wiz</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.wiz</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.wiz</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.wiz</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\.</string>
                    <key>name</key>
                    <string>constant.character.escape.wiz</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.wiz</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.wiz</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.wiz</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\.</string>
                    <key>name</key>
                    <string>constant.character.escape.wiz</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.source.wiz</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\*/\n?</string>
            <key>name</key>
            <string>comment.block.source.wiz</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.source.wiz</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(//).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.source.wiz</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(let|not|var|def|bank|in|byte|word|if|is|then|elseif|else|compare|bit|to|end|goto|far|call|sleep|hibernate|nop|return|resume|loop|until|while|do|package|pop|push|via|when|break|continue|abort|include|embed|func|task|inline|unroll)\b</string>
            <key>name</key>
            <string>keyword.control.wiz</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b(zero|carry|interrupt|overflow|negative|decimal|a|b|c|d|e|h|l|sp|hl|af|bc|de|x|y|s|p)\b</string>
            <key>name</key>
            <string>support.class.wiz</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\[|\]|\=(?!\=)|\!</string>
            <key>name</key>
            <string>variable.language.wiz</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\+[+#]?|-[-#]?|%|\*|\/|\^|&amp;|\||==|~(=?)|&lt;(=|&gt;|&lt;(-|&lt;#?)?)?|&gt;(=|&gt;(-|&gt;#?)?)?|@|\:|,</string>
            <key>name</key>
            <string>keyword.operator.wiz</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.wiz</string>
    <key>uuid</key>
    <string>93E017CC-6F27-11D9-90EB-000DFACEABD8</string>
</dict>
</plist>
